### ISSUE TITLE
Libary not running with python 3.9

### ISSUE THREAD

**Issue by katrinsieber** [baseplate-admin/flask_strip_whitespace#2]
Hi, I tried to use your libary. But when it was started I got this error message:

File "/usr/local/lib/python3.9/dist-packages/flask_strip_whitespace/middlewares/__init__.py", line 31, in HTMLStripWhiteSpaceMiddleware
 config: Optional[Dict[str, bool | str | List[str]]] = {},
TypeError: unsupported operand type(s) for |: 'type' and 'type'

Can you repair it?

Best regards, Katrin

**Comment by baseplate-admin** [comment]
hi there,

this library has been unmaintained for quite a while... 

gimme some time to fix this 😀

**Comment by baseplate-admin** [comment]
Hi there,

I have published version 0.1.0 to pypi

Could you please retest and see if it works?

**Comment by katrinsieber** [comment]
Hi, thanks for the fast fix. I don't get the eroor anylonger.

**Comment by baseplate-admin** [comment]
Thank you for reporting the error. May we close the issue?
